name: Build Xiaomi Mix2s (Based AOSP A15) (Kernel 4.19)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "xiaomi_mix2s"
  DEVICE_CODENAME : "polaris"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/duckyduckG/android_kernel_xiaomi_sdm845_419.git"
  KERNEL_BRANCH : "perf"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/sdm845-perf_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/refs/heads/susfs-main/kernel/setup.sh"
  KERNELSU_BRANCH : "susfs-main"
  KERNELSU_NAME : "KernelSU"

  KERNELSU_AUTO_GET : "false"
  KERNELSU_AUTO_FORK : "" # magic, rsuntk and sukisu

  SUSFS_ENABLE : true
  SUSFS_FIXED : true
  SUSFS_UPDATE : true

  AK3_SOURCE : "https://github.com/JackA1ltman/OP8_AnyKernel3.git"
  AK3_BRANCH : "main"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "based_aosp_a15"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.

  KERNELSU_METHOD: "shell" # shell, manual and only.

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "mi_kernel" # [your_branch] -> main

  SUSFS_FOLDER_FIXED: "mix2s_aosp_a15_419" # Fill in your patch prefix directory here. Leave it blank if there isn't one. -> your_folder
  SUSFS_155_FIXED: "susfs_155_fixed,stat_fixed" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2 (Only v1.5.5 SuSFS)
  SUSFS_LATEST_FIXED: "sched_fixed" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2

  REKERNEL_ENABLE: "false" # if u need Re:Kernel.

  HOOK_METHOD: "tracepoint" # manual hook method,can choice : normal, syscall and tracepoint.
  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.

  KPM_ENABLE: "false" # Only use it for SukiSU-Ultra.
  KPM_FIX: "false" # Fix Error When Enabling KPM.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "true" # Merge config files.
  MERGE_CONFIG_FILES: "vendor/xiaomi/sdm845-common.config,vendor/xiaomi/polaris.config"

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

jobs:
  build-kernel:
    name: Xiaomi Mix2s (Based AOSP A15) (Kernel 4.19)
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: â° Checkout repository
        uses: actions/checkout@v4

      - name: âŒ›ï¸ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: âš™ï¸ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: ğŸ”— Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: ğŸª› Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel

          # Get neccssary components
          git clone https://github.com/duckyduckG/kernel_techpack_mi845_419.git -b main techpack/mi845
          git clone https://github.com/duckyduckG/devicetree_qcom-sdm845_419.git -b main arch/arm64/boot/dts/qcom-sdm845
          git clone https://github.com/duckyduckG/devicetree_xiaomi_419.git -b master-dipper arch/arm64/boot/dts/xiaomi

          # Build config
          echo "CONFIG_COMPAT_VDSO=y" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_LTO_NONE=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_SHADOW_CALL_STACK=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          echo "CONFIG_RELR=n" >> ./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}

      - name: ğŸª Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: ğŸ§° Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: ğŸš€ Build Process
        uses: ./.github/workflows/build-process

      - name: ğŸ”© Pack Process
        uses: ./.github/workflows/pack-process

      - name: âœï¸ Upload Artifacts
        uses: ./.github/workflows/upload-files
