name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # OPPO
  ## Oneplus
  build-oneplus-8-series-oos13-a13-xtd:
    name: "Onelus 8 Series (OxygenOS 13 A13) (XTD Kernel)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-oneplus-8-series-oos13-a13-xtd.yml
    secrets: inherit

  # Xiaomi
  build-xiaomi-mix2s-evox10-a15:
    name: "Xiaomi Mix2s (Evolution X 10 A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-xiaomi-mix2s-evox10-a15.yml
    secrets: inherit

  build-xiaomi-11ultra-hyperos-a14:
    name: "Xiaomi 11 Ultra (HyperOS A14)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-xiaomi-11ultra-hyperos-a14.yml
    secrets: inherit

  build-xiaomi-11-evox-a16:
    name: "Xiaomi 11 (Evolution X 11 A16)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-xiaomi-11-evox-a16.yml
    secrets: inherit

  ## Redmi
  build-redmi-k20pro-aosp-a15-sovietstaross:
    name: "Redmi K20 Pro (Soviet-Star-OSS)(Based-AOSP A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-redmi-k20pro-aosp-a15-sovietstaross.yml
    secrets: inherit

  build-redmi-8-aosp-a15-419:
    name: "Redmi 8 (Based-AOSP A15) (Kernel 4.19)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-redmi-8-aosp-a15-419.yml
    secrets: inherit

  build-redmi-note7-aosp-a15:
    name: "Redmi Note 7 (Based AOSP A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-redmi-note7-aosp-a15.yml
    secrets: inherit

  # Samsung
  build-samsung-note10plus-oneui-a15:
    name: "Samsung Note 10 Plus (OneUI A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-samsung-note10plus-oneui-a15.yml
    secrets: inherit

  build-samsung-note10-oneui-a15:
    name: "Samsung Note 10 (OneUI A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-samsung-note10-oneui-a15.yml
    secrets: inherit

  # Smartisan
  build-smartisan-u3pro-lineageos18-a11:
    name: "Smartisan U3 Pro (Lineage OS 18 A11)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-smartisan-u3pro-lineageos18-a11.yml
    secrets: inherit
