name: Build Xiaomi 11 Ultra (HyperOS A14)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "xiaomi_11_ultra"
  DEVICE_CODENAME : "star"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/EndCredits/android_kernel_xiaomi_sm8350-miui.git"
  KERNEL_BRANCH : "new-rebase"

  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : ""
  GCC_64_BRANCH : ""
  GCC_32_SOURCE : ""
  GCC_32_BRANCH : ""

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/star_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : "https://github.com/rsuntk/KernelSU.git"
  KERNELSU_BRANCH : "susfs-main"
  KERNELSU_NAME : "KernelSU"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true
  SUSFS_UPDATE : true

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "hyperos_a14"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.

  KERNELSU_METHOD: "only" # shell, manual and only.

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "mi_kernel" # [your_branch] -> main

  SUSFS_FOLDER_FIXED: "mi11u_hyperos" # Fill in your patch prefix directory here. Leave it blank if there isn't one. -> your_folder
  SUSFS_155_FIXED: "hyperos_a14_fixed" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2 (Only v1.5.5 SuSFS)
  SUSFS_LATEST_FIXED: "" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2

  REKERNEL_ENABLE: "false" # if u need Re:Kernel.

  HOOK_METHOD: "syscall" # manual hook method,can choice : normal, syscall and tracepoint.
  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.

  KPM_ENABLE: "false" # Only use it for SukiSU-Ultra.
  KPM_FIX: "false" # Fix Error When Enabling KPM.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "false" # Merge config files.
  MERGE_CONFIG_FILES: "vendor/debugfs.config,vendor/lahaina_QGKI.config"

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

jobs:
  build-kernel:
    name: Xiaomi 11 Ultra (HyperOS A14)
    runs-on: ubuntu-latest # u can changed to ubuntu 22.04, and need container set ubuntu-latest
    # container: archlinux/archlinux:latest # if u need use arch linux -> archlinux/archlinux:latest or ubuntu 20.04 -> ubuntu:focal
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: â° Checkout repository
        uses: actions/checkout@v4

      - name: âŒ›ï¸ Execuate common process
        uses: ./.github/workflows/build-env

      - name: âš™ï¸ Compilation preparation
        uses: ./.github/workflows/build-ready

      - name: ğŸ”— Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: ğŸª› Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel
          # Nothing

      - name: ğŸª Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: ğŸ§° Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: ğŸš€ Build Process
        uses: ./.github/workflows/build-process

      - name: ğŸ”© Pack Process
        uses: ./.github/workflows/pack-process

      - name: âœï¸ Upload Artifacts
        uses: ./.github/workflows/upload-files
