name: Build Xiaomi 11 (Evolution X 11 A16)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "xiaomi_11"
  DEVICE_CODENAME : "venus"

  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld"

  KERNEL_SOURCE : "https://github.com/kamikaonashi/kernel_xiaomi_venus.git"
  KERNEL_BRANCH : "16"

  CLANG_SOURCE : "https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git"
  CLANG_BRANCH : "lineage-20.0"

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "vendor/lahaina-qgki_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh"
  KERNELSU_BRANCH : "susfs-main"
  KERNELSU_NAME : "KernelSU"

  SUSFS_ENABLE : true
  SUSFS_FIXED : true
  SUSFS_UPDATE : true

  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "evolution_x_a16"

  # Other env
  PYTHON_VERSION: "3" # Only 2(Ubuntu 22.04 and Ubuntu 20.04) or 3(Any OS Versions).

  PACK_METHOD: "Anykernel3" # Anykernel3 need SOURCE and BRANCH, MKBOOTIMG needn't it.

  KERNELSU_METHOD: "shell" # shell, manual and only.
  KERNELSU_SUS_PATCH: "false" # if u need manual susfs patch to kernelsu.

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches" # [your_name]/[your_patch] -> gooder123/NonGKI_Patcher
  PATCHES_BRANCH: "mi_kernel" # [your_branch] -> main

  SUSFS_FOLDER_FIXED: "mi8_evox_a16" # Fill in your patch prefix directory here. Leave it blank if there isn't one. -> your_folder
  SUSFS_155_FIXED: "susfs_155_fixed" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2 (Only v1.5.5 SuSFS)
  SUSFS_LATEST_FIXED: "susfs_157_fixed,susfs_1510_fixed" # Fill in your patches here. If there are multiple patches, please separate them with a comma. Leave it blank if there isn't one. -> patch1,patch2

  REKERNEL_ENABLE: "true" # if u need Re:Kernel.

  HOOK_METHOD: "tracepoint" # manual hook method,can choice : normal, syscall and tracepoint.
  HOOK_OLDER: "false" # contain backport older patch and syscall older patch.

  KPM_ENABLE: "true" # Only use it for SukiSU-Ultra.
  KPM_FIX: "false" # Fix Error When Enabling KPM.
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux" # patch exec file source -> raw.githubusercontent.com/Test/Test/patch .

  GENERATE_DTB: "false" # if u kernel need DTB , but cannot auto generate it. (Only Anykernel3).
  GENERATE_CHIP: "qcom" # only supported for qcom and mediatek.

  BUILD_DEBUGGER: "false" # Output build errors.
  SKIP_PATCH: "false" # Ignore errors found in Patch Debugger.

  BUILD_OTHER_CONFIG: "true" # Merge config files.
  MERGE_CONFIG_FILES: "vendor/venus_QGKI.config,vendor/xiaomi_QGKI.config"

  FREE_MORE_SPACE: "false" # if u want get more space, enabled it.

jobs:
  build-kernel:
    name: Xiaomi 11 (Evolution X 11 A16)
    runs-on: ubuntu-latest # u can changed to ubuntu 22.04, and need container set ubuntu-latest
    # container: archlinux/archlinux:latest # if u need use arch linux -> archlinux/archlinux:latest or ubuntu 20.04 -> ubuntu:focal
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: â° Checkout repository
        uses: actions/checkout@v4

      - name: âŒ›ï¸ Execuate common process
        uses: ./.github/workflows/build-env

      - name: âš™ï¸ Compilation preparation
        uses: ./.github/workflows/build-ready

      - name: ğŸ”— Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: ğŸ§° Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: ğŸš€ Build Process
        uses: ./.github/workflows/build-process

      - name: ğŸ”© Pack Process
        uses: ./.github/workflows/pack-process

      - name: âœï¸ Upload Artifacts
        uses: ./.github/workflows/upload-files
